<?php

namespace AppBundle\Controller;

use AppBundle\Entity\User;
use AppBundle\Form\UserEditForm;
use AppBundle\Form\UserRegistrationForm;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;

class UserController extends Controller
{
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/register", name="user_register")
     */
    public function registerAction(Request $request)
    {
        // wygenerowanie formularza rejestracyjnego
        $form = $this->createForm(UserRegistrationForm::class);

        $form->handleRequest($request);
        // sprawdzenie, czy formularz został poprawnie wypełniony
        if ($form->isValid()) {
            /** @var User $user */
            $user = $form->getData(); // pobranie danych z formularza

            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $user->getAvatarUri(); // pobranie przesłanego obrazu avatara

            if ($file) {
                // upload pliku avatara
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                $folderName = 'uploads/avatars/';

                $file->move(
                    $this->getParameter('avatars_dir'),
                    $fileName
                );
            } else {
                // ustawienie domyślnego avatara na podstawie płci
                $gender = $user->getGender();
                $fileName = 'default-'.$gender.'.jpg';
                $folderName = 'images/';
            }

            // przypisanie obrazu avatara do użytkownika
            $user->setAvatarUri($folderName.$fileName);

            $em = $this->getDoctrine()->getManager();
            // zapisanie obiektu użytkownika przez ORM Doctrine 2 do bazy danych
            $em->persist($user);
            $em->flush();

            // ustawienie wiadomości informującej o pomyślnej rejestracji
            $this->addFlash('success', 'Welcome '.$user->getEmail());

            // automatyczne zalogowanie oraz przeniesienie do strony tablicy
            return $this->get('security.authentication.guard_handler')
                ->authenticateUserAndHandleSuccess(
                    $user,
                    $request,
                    $this->get('app.security.login_form_authenticator'),
                    'main'
                );
        }
        // jeśli walidacja się nie powiodła, następuje wygenerowanie formularza z błędami
        return $this->render('user/register.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/users/{id}", name="user_show")
     */
    public function showAction(User $user)
    {
        $em = $this->getDoctrine();
        $friendsReq1 = $em->getRepository('AppBundle:FriendsRequest')->findOneBy([
            'userSend' => $this->getUser()->getId(),
            'userRecipient' => $user->getId(),
        ]);

        $areFriends = $em->getRepository('AppBundle:Friends')->areFriends(
            $this->getUser(),
            $user
        );

        return $this->render('user/show.html.twig', array(
            'user' => $user,
            'inviteBtn' => !isset($friendsReq1),
            'acceptBtn' => isset($friendsReq2),
            'areFriends' => $areFriends,
        ));
    }

    /**
     * @Route("/account", name="user_account")
     */
    public function accountAction()
    {
        $user = $this->getUser();

        return $this->render('user/show.html.twig', array(
            'user' => $user
        ));
    }

    /**
     * @Route("/users/{id}/edit", name="user_edit")
     */
    public function editAction(User $user, Request $request)
    {
        $form = $this->createForm(UserEditForm::class, $user);

        $form->handleRequest($request);
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash('success', 'User Updated!');

            return $this->redirectToRoute('user_edit', [
                'id' => $user->getId()
            ]);
        }

        return $this->render('user/edit.html.twig', [
            'userForm' => $form->createView()
        ]);

    }
}
